---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1rh7m647fsdmm7a2yy6un6fn845e8gmfxwnjz0gtdku77n0jsjsyqfqegpf
  - path_regex: nixos/secrets/.*\.yaml$
    key_groups:
      - age:
          # admin
          - age1rh7m647fsdmm7a2yy6un6fn845e8gmfxwnjz0gtdku77n0jsjsyqfqegpf
          # laptop
          - age1aee7tp00ae7vngf50jn2zd9h2ddmcyaenkv4w3vlgec5frmvrc8qg64423
          # template
          - age1v9tajgxsj7zkauwf6p50qk3ngtlqspqr89cl83a6cfkd20835etq4frnmj
          # racknerd-vps
          - age1qsst00d5j0t57ajzclj58kmxhfmtng58r3dez8rtu47nqmcjg4pqt9204k
