---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager/ks.yaml
  - bitwarden-cli/ks.yaml
  - cilium/ks.yaml
  - crd-schema-publisher/ks.yaml
  - envoy-gateway/ks.yaml
  - external-secrets/ks.yaml
  - flux-instance/ks.yaml
  - flux-operator/ks.yaml
  - gateway-api/ks.yaml
  - metrics-server/ks.yaml
  - reloader/ks.yaml
  - rook-ceph/ks.yaml
  - snapshot-controller/ks.yaml
  - spegel/ks.yaml
  - tofu-controller/ks.yaml
