apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-credentials
    namespace: security
type: Opaque
stringData:
    bw_clientid: ENC[AES256_GCM,data:Hf43d2H1FkH+nUyxXxEQ87Umo+0W7tGhpNG4FwYBMRZ1osXsaqHCWd4=,iv:Qx52zULjpA48b19sttRI5PjhnP8LvicE8Q3GppVvypo=,tag:tJ4bA+J5GaxxgrnkL5Ns7Q==,type:str]
    bw_clientsecret: ENC[AES256_GCM,data:7PR93/NdoGYxmz6lrhQUTwykDYt3+nBMnsQbdfX/,iv:raSKRDy3kvLkRQ9J8ExWWz0hGsTMm46ZMy2HglBa5PU=,tag:243+g+I7ZOMXwh0NkWeDpQ==,type:str]
    bw_password: ENC[AES256_GCM,data:zJ8ufCPt0iDJtUJZ0KAJlS8fZLQ1d3MCpzCRLihOjiKySBBNdJl7z7lwqcKzdySxAJ8vcwwn,iv:b76B2nWft9ImbxqckR3VtXiAtiVQsioURdgcwAkFL64=,tag:ElABQzOAS5Pmpu5ok5PfyA==,type:str]
    bw_host: ENC[AES256_GCM,data:rlZ9dapAk+16fKJkWUPUDUTU1JzR5A==,iv:CplOXZysT8dttnfXHQoMnPa6CpJ4J+UIAWpz2prZz8A=,tag:+VsSENhzpFdWpJZ8poxcLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UkVyeDN5RmROSHJTdmJQ
            RkNKQkgvZitvb3lZT3lUTTBLbWR5R1F5RUc4CmlkbWNMMnI4eDV0d0k2bDJ3QXph
            VUR4bmFhSzZGTU1CWFduODV3TURXYnMKLS0tIC9semFTZFZXd21RTXJnVDZRamRm
            TlRMQ3VGdE9uNmJvL3YzdHlXVVhQTXcKRq89tQ5ewCmJcXGv5EXFL3/HeeeIJWir
            4YvHvFvZOfytsp+47K8+g1TzAckFsNb0t9jso0AdORIWLTox3Ix4vA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rh7m647fsdmm7a2yy6un6fn845e8gmfxwnjz0gtdku77n0jsjsyqfqegpf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T01:50:50Z"
    mac: ENC[AES256_GCM,data:0BKrK35n3CVFajKFmj9UN0iWDYtwInMuFmG/HARyDzXDTtWV+nxCmllcNgXjaZqLA+5jZchBxiDdgkSgekGjk82eGPuot4w6LDG3zTi+VNM0i8W4AKzxVkoLIGzt2lg98Gukr6Gi7enR75IV8vdbahZJu1Z0qZccqkVjIKco7HQ=,iv:FXBA4lC3n9/ZpXKiT9eglc8+KEeXS9q323VAEQ0rBzM=,tag:56pJcm6s810i/EepNFmLjA==,type:str]
    version: 3.13.3
