apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-credentials
    namespace: security
type: Opaque
stringData:
    bw_clientid: ENC[AES256_GCM,data:D3uUvFPjEmMbVRgyEJ1so90oEEmr,iv:CLQ1Y7N7oGbMpIs1yLQhBZnWl02hBgfzmFGJ/4cQozs=,tag:O0m9ce4CSYVsyV1f4CFkYQ==,type:str]
    bw_clientsecret: ENC[AES256_GCM,data:6YP7bFhP0QoO5yo0/PjPcuLeKAmB+JGIuQ==,iv:yIA78ToaOzB8j2wuD6nYnG/EQQ49k770ju/MoOG1ZS4=,tag:zS3tdtFRneLKYIOYiSfuIw==,type:str]
    bw_password: ENC[AES256_GCM,data:cbK7vrsWcakKSJAfLkv9qgq3KZ/wA0eH29UC,iv:LgcxaadovYZcZ4OHcDr0jGCZ17EQ05QlCB+VL3DPNGk=,tag:zlSLXRZ+eLP8cYdDtqNoYA==,type:str]
    bw_host: ENC[AES256_GCM,data:tpLgpYYo5/mdoE+YwoDe7jCpie4SRTKoPs1ziIdvZg==,iv:5432Sle7dUqZITtD9AHfy4RN/Z2SQjDjnLggtpfpICY=,tag:/Xb6oquEXUNefjjCFNg5IQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UkVyeDN5RmROSHJTdmJQ
            RkNKQkgvZitvb3lZT3lUTTBLbWR5R1F5RUc4CmlkbWNMMnI4eDV0d0k2bDJ3QXph
            VUR4bmFhSzZGTU1CWFduODV3TURXYnMKLS0tIC9semFTZFZXd21RTXJnVDZRamRm
            TlRMQ3VGdE9uNmJvL3YzdHlXVVhQTXcKRq89tQ5ewCmJcXGv5EXFL3/HeeeIJWir
            4YvHvFvZOfytsp+47K8+g1TzAckFsNb0t9jso0AdORIWLTox3Ix4vA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rh7m647fsdmm7a2yy6un6fn845e8gmfxwnjz0gtdku77n0jsjsyqfqegpf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T01:54:39Z"
    mac: ENC[AES256_GCM,data:/hecsuOprGwYSn6fGk2tdrlHsQ7rEeR7BMQD2PWlS07yZz+/Xu7kyZdDsuv6uKkDD8I/SjHhHVyY8MLufTGJQuyMdR1mAwDJn7UPzAfM2LiJa/uHYApSTbYmBB4rNoVdWyRNLlp6COywhV9AGWnaDRAa+RYyVSmMhXD/Hn5B1ew=,iv:Hn5O1ZKgEAW4Essx6i74AQqiuz8BtYMfqLJmkm7isaE=,tag:BTTFoZRXbxDqKRSyDvs3lQ==,type:str]
    version: 3.13.3
