- name: Docker Login
  hosts: "*"
  become: false
  vars:
    docker_password: "{{ lookup('pipe', 'bw get item 3726555b-0ffc-442b-b66a-b257016f6ab9 | jq -r \".login.password // .fields[0].value // .notes // empty\"') }}"
  tasks:
    - name: Log into DockerHub
      community.docker.docker_login:
        username: mafyuh
        password: "{{ docker_password }}"
