---
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
clusterName: home-cluster
endpoint: https://192.168.86.53:6443
# renovate: depName=siderolabs/talos datasource=github-releases
talosVersion: v1.13.9
# renovate: depName=kubernetes/kubernetes datasource=github-releases
kubernetesVersion: v1.36.3
additionalApiServerCertSans: &sans
  - 127.0.0.1
additionalMachineCertSans: *sans
cniConfig:
  name: none
nodes:
  - hostname: talos-1.laborda.me
    ipAddress: 192.168.86.53
    controlPlane: true
    installDisk: /dev/sda
controlPlane:
  schematic:
    customization:
      extraKernelArgs:
        - -init_on_alloc
        - -selinux
        - apparmor=0
        - init_on_alloc=0
        - init_on_free=0
        - intel_iommu=on # PCI Passthrough
        - iommu=pt # PCI Passthrough
        - mitigations=off
        - security=none
        - talos.auditd.disabled=1
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/realtek-firmware
  patches:
    # Disable search domain (DHCP is used)
    - |-
      machine:
        network:
          disableSearchDomain: true
    # Customize containerd (Spegel)
    - |-
      machine:
        files:
          - path: /etc/cri/conf.d/20-customization.part
            op: create
            content: |
              [plugins."io.containerd.cri.v1.images"]
                discard_unpacked_layers = false
    # Enable feature
    - |-
      machine:
        features:
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false
          kubernetesTalosAPIAccess:
            allowedKubernetesNamespaces:
              - system-upgrade
              - actions-runner-system
            allowedRoles:
              - os:admin
            enabled: true
    # Configure cluster
    - |-
      cluster:
        allowSchedulingOnControlPlanes: true
        apiServer:
          extraArgs:
            feature-gates: "ImageVolume=true,MutatingAdmissionPolicy=true,ResourceHealthStatus=true"
            runtime-config: "admissionregistration.k8s.io/v1beta1=true"
        coreDNS:
            disabled: false
        proxy:
          disabled: true
    # Configure etcd
    - |-
      cluster:
        etcd:
          advertisedSubnets:
            - 192.168.86.0/24
    # Configure kube-controller-manager metrics
    - |-
      cluster:
        controllerManager:
          extraArgs:
            bind-address: "0.0.0.0"
    # Configure kube-scheduler metrics
    - |-
      cluster:
        scheduler:
          extraArgs:
            bind-address: "0.0.0.0"
